// src/app/program-type.enum.ts
export enum ProgramType {
  EDUCATION = 'EDUCATION',
  HEALTHCARE = 'HEALTHCARE',
  FOOD_AND_NUTRITION = 'FOOD_AND_NUTRITION',
  WOMEN_EMPOWERMENT = 'WOMEN_EMPOWERMENT',
  DISASTER_RELIEF = 'DISASTER_RELIEF',
  COMMUNITY_DEVELOPMENT = 'COMMUNITY_DEVELOPMENT',
  DIFFERENTLY_ABLED = 'DIFFERENTLY_ABLED'
}
